import math
a=int(input("enter first number"))
b=int(input("enter first number"))
c=int(input("enter first number"))
print("largest number is",(max(a,b,c)))
f=math.sqrt(a)
g=math.sqrt(b)
h=math.sqrt(c)
print("square root of",a,"is",f)
print("square root of",b,"is",g)
print("square root of",c,"is",h)
